plt.figure(ifigure)
    ifigure += 1
    index = np.arange(len(x))
    # print(index)
    # print(y)
    rect = plt.bar(index, y, width=0.8)
    autolabel(rect)
    plt.xlabel('Number of processes')
    plt.ylabel('Time in seconds')
    plt.xticks(index, x)
    plt.title('Time taken for n=' + str(n))
    plt.show()